### PR TITLE
example: add `Flask-IIIF` extension

### PR DESCRIPTION
**Pull request by drjova**

### CODE REVIEW

**Comment by jirikuncar** [comment]
@drjova thanks. can you also remove the `/demo` folder?

**Comment by drjova** [comment]
it's not in my branch https://github.com/drjova/iugw2015/tree/merged :/

**Comment by jirikuncar** [comment]
@drjova because you have to rebase first ;)

**Comment by drjova** [comment]
true :P :+1:

**Comment by jirikuncar** [comment]
ping @drjova ;)

**Comment by drjova** [comment]
I've already rebased :)

**Comment by jirikuncar** [comment]
:+1:

**Pull request merged**
